[[bin]]
name = "fa2b2"

[package]
name = "fa2b2"
version = "0.1.0"
authors = ["Roel Kluin <r.kluin@nki.nl>"]
edition = "2021"

[lib]
path = "src/lib.rs"
crate-type = ["rlib", "dylib"]

[dependencies]
bio = "*"
flate2 = "0.2"
csv = "0.14"
arrayvec = "0.3.12"
bincode = "1.3.3"
clap = "2.19.1"
bit_reverse = "0.1.7"
derive-new = "0.5"
num-traits = "0.2"
num = "0.2"
rand = "0.5"
lazy_static = "1.3.0"
serde = "1.0.130"
anyhow = "1.0.48"

